DROP TABLE IF EXISTS chamados;
CREATE TABLE chamados (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  laboratorio TEXT,
  micro INTEGER,
  problema TEXT,
  FOREIGN KEY (id) REFERENCES alunos (id)
);
DROP TABLE IF EXISTS alunos;
CREATE TABLE alunos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES user (id)
);